name: Go

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y libbtrfs-dev libdevmapper-dev libgpgme-dev pkg-config build-essential libdpkg-dev

      - name: Build
        run: go build -o abrootv2

      - name: Test
        run: go test -v ./tests/...

      - name: Compress
        run: tar -czvf abrootv2.tar.gz abrootv2

      - name: Compress-manpage
        run: tar -czvf abroot-man.tar.gz man/man1/abroot.1

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            abrootv2.tar.gz
            abroot-man.tar.gz

  test:
    name: Integration Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /dev:/dev:rslave
        - /proc:/proc
        - /:/run/host
      options: --privileged -it
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y parted mount kpartx kmod dosfstools libbtrfs-dev libdevmapper-dev libgpgme-dev pkg-config libdpkg-dev udev curl

      - name: Extract Build
        run: |
          tar -xzvf artifacts/abrootv2.tar.gz -C .

      - name: Create Virtual Disk Image
        run: |
          dd if=/dev/zero of=vos.img bs=1M count=3328

      - name: Setup Loop Device
        id: setup_loop
        run: |
          loop_device=$(losetup -Pf --show vos.img)
          echo "loop_device=$loop_device" >> $GITHUB_ENV

      - name: Create Partitions
        run: |
          parted ${loop_device} mklabel gpt
          parted ${loop_device} mkpart vos-var ext4 1MiB 1025MiB
          parted ${loop_device} mkpart vos-a ext4 1025MiB 2049MiB
          parted ${loop_device} mkpart vos-b ext4 2049MiB 3073MiB
          parted ${loop_device} mkpart vos-boot ext4 3073MiB 3173MiB
          parted ${loop_device} mkpart vos-efi fat32 3173MiB 3273MiB

      - name: Format Partitions
        run: |
          mkfs.ext4 ${loop_device}p1 -L vos-var
          mkfs.ext4 ${loop_device}p2 -L vos-a
          mkfs.ext4 ${loop_device}p3 -L vos-b
          mkfs.ext4 ${loop_device}p4 -L vos-boot
          mkfs.vfat ${loop_device}p5 -n vos-efi

      - name: Synchronize Partitions
        run: |
          partprobe ${loop_device}
          sleep 5
          udevadm trigger
          udevadm settle

      - name: Check Loop Device
        run: |
          losetup -a
          ls -l /dev/disk/by-label
          blkid

      - name: Test Mount
        run: |
          mount LABEL=vos-var /mnt
          umount /mnt

      - name: Configure distrobox
        run: |
          curl -s https://raw.githubusercontent.com/89luca89/distrobox/1.7.1/install | sh
          distrobox create -i ghcr.io/vanilla-os/pico:main -n pico

      - name: List devices
        run: |
          distrobox enter -e pico lsblk -J -o "NAME,FSTYPE,LABEL,MOUNTPOINT,UUID"
          exit
          
      - name: Run Integration Test
        run: |
          ./abrootv2 status

  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest
    if: github.repository == 'vanilla-os/ABRoot' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            abrootv2.tar.gz
            abroot-man.tar.gz
